### ISSUE TITLE
Spell check in comments

### ISSUE THREAD

**Issue by PierreMarchand20** [AtomLinter/linter-spell-latex#30]
I have the following behavior: 
![capture d ecran 2018-01-19 a 18 40 53](https://user-images.githubusercontent.com/15056323/35163841-55d6fa72-fd48-11e7-9d56-7d3122435b20.png)

Would it be possible to not have this behavior ? I checked the scope of `\lVert` for example:
![capture d ecran 2018-01-19 a 18 42 30](https://user-images.githubusercontent.com/15056323/35163930-9488f108-fd48-11e7-9b93-22b998fdb9d4.png),
so it seems possible to discard latex commands in comments since they are part of `meta.function.environment.general.latex`.

**Comment by yitzchak** [comment]
Spell checking in comments can be disabled in the settings page

**Comment by PierreMarchand20** [comment]
Well, actually, I want it to do the spell-check. But it does not recognize latex commands in comments so that, as soon as I comment a part of my file, I get a lot of spell-ckeck warning because of the latex commands.

**Comment by Aerijo** [comment]
I believe he's using my grammar. If there is anything I need to change, let me know.

I probably won't do too much more to that grammar though, on account of `tree-sitter` looking ready to arrive some time this year. 

@yitzchak do you have any tips on developing this new grammar type? I [can't even load it](https://discuss.atom.io/t/help-setting-up-tree-sitter-grammar-development/52113).

**Comment by yitzchak** [comment]
@PierreMarchand20 It is currently not possible to recognize LaTeX syntax inside comments since that is not part of any LaTeX syntax package for Atom.

@Aerijo I have only just started looking into `tree-sitter`. I have a basic setup in `tree-sitter-latex`, but I have not uploaded it yet. Not sure how far I will get since LaTeX is not a context free LR grammar. Having a tree sitter grammar for LaTeX would also be useful for an `ide-latex` package.
